#!/bin/bash

echo "========================================="
echo "  Push Cleaned Git History to GitHub"
echo "========================================="
echo ""
echo "⚠️  This will FORCE PUSH and OVERWRITE remote history!"
echo "⚠️  All secrets have been removed from all commits"
echo ""
echo "Current status:"
echo "  - Private key: REDACTED in all commits ✅"
echo "  - Old wallet: REDACTED in all commits ✅"
echo "  - Local history: CLEANED ✅"
echo "  - Remote: NOT YET UPDATED ⚠️"
echo ""
echo "========================================="
echo ""

# Method 1: GitHub CLI (recommended)
echo "Method 1: GitHub CLI (Recommended)"
echo "-----------------------------------"
echo "If you have 'gh' CLI installed:"
echo ""
echo "  gh auth login"
echo "  git push --force --all"
echo ""

# Method 2: Personal Access Token
echo "Method 2: Personal Access Token"
echo "-------------------------------"
echo "If you have a GitHub PAT:"
echo ""
echo "  git remote set-url origin https://YOUR_TOKEN@github.com/mjfendin/siggy-chess.git"
echo "  git push --force --all"
echo ""
echo "Get token at: https://github.com/settings/tokens"
echo "Required scopes: repo (full control)"
echo ""

# Method 3: SSH Key
echo "Method 3: SSH Key"
echo "-----------------"
echo "If you have SSH key configured:"
echo ""
echo "  git remote set-url origin git@github.com:mjfendin/siggy-chess.git"
echo "  git push --force --all"
echo ""

echo "========================================="
echo ""
echo "After push, verify on GitHub:"
echo "  https://github.com/mjfendin/siggy-chess/blob/main/ritual-agent.py"
echo ""
echo "You should see 'REDACTED_PRIVATE_KEY' instead of actual key"
echo ""
